#####################################################################################################
#   /\/\  (_) _ __    ___   /\ \ \  ___  __   __  __ _    / __\  ___   _ __   / _|(_)  __ _  ___    #
#  /    \ | || '_ \  / _ \ /  \/ / / _ \ \ \ / / / _` |  / /    / _ \ | '_ \ | |_ | | / _` |/ __|   #
# / /\/\ \| || | | ||  __// /\  / | (_) | \ V / | (_| | / /___ | (_) || | | ||  _|| || (_| |\__ \   #
# \/    \/|_||_| |_| \___|\_\ \/   \___/   \_/   \__,_| \____/  \___/ |_| |_||_|  |_| \__, ||___/   #
#                                                                                     |___/         #
#####################################################################################################

# MineNova Huevo Puente
#
# Do you need a plugin that recreates the function of the Bridge Egg and
# the Bridge Ball? You found what you were looking for! This lightweight
# plugin is going to make your life easier if your Bedwars plugin isn't
# working correctly or if you have plans to create a minigame. And the
# best part is that it's editable!

# This is my first plugin, I will greatly appreciate your reviews.
#
# Dev. ZxyretrohackyxZ

# Permission Command:
#
# /bridge Egg/Ball · bridge.command

items:
  eggName: "&aBridge Egg"
  ballName: "&aBridge Ball"

messages:
  noPermission: "&cYou don't have permission to use this command."
  usage: "&eUse: /Bridge Egg\n/Bridge Ball"
  bridgeEggGiven: "&aYou have received the bridge egg!"
  bridgeBallGiven: "&aYou have received the bridge ball!"